print("This is a mad lib, please input the type of word the program asks for as it asks you for them.")
name = input("Noun: ")
adj_1 = input("Adjective: ")
occupation = input("Occupation: ")
verb_1 = input("Verb: ")
original_plural_noun = input("Plural noun: ")
noun_1 = input("Noun referring to food: ")
verb_2 = input("Verb ending in 'ed': ")
weapon = input("Weapon: ")
clothing = input("Article of clothing: ")
workout = input("Type of workout: ")
prop_noun = input("Proper noun referring to a place: ")
music = input("Music Genre: ")
sound = input("Sound: ")
organ = input("Human organ: ")
print()

print("Your name is %s." % name)
print("You are a %s %s." % (adj_1, occupation))
print("Today you must %s the %s." % (verb_1, original_plural_noun))
print("The reason you are doing this is because the %s ate your %s." % (original_plural_noun, noun_1))
print("This was the last straw for you, they have went over the line, and for that they must be %s." % verb_2)
print("You arm yourself with a %s and put on your favorite %s." % (weapon, clothing))
print("After all of this, you do some extreme %s." % workout)
print("When you finally arrive at %s’s %s you start hyping yourself up by listening to %s music." % (original_plural_noun, prop_noun, music))
print("When you enter you have a glorious battle with %s that ends in your victory." % original_plural_noun)
print("As a sign of ultimate dominance you let out a fierce %s." % sound)
print("After the battle, you return home and take a long nap to rest your troubled %s." % organ)
