print("This is a mad lib, please input the type of word the program asks for as it asks you for them.")
name = input("Noun: ")
adj_1 = input("Adjective: ")
occupation = input("Occupation: ")
verb_1 = input("Verb: ")
original_plural_noun = input("Plural noun: ")
noun_1 = input("Noun referring to food: ")
verb_2 = input("Verb ending in 'ed': ")
weapon = input("Weapon: ")
clothing = input("Article of clothing: ")
workout = input("Type of workout: ")
prop_noun = input("Proper noun referring to a place: ")
music = input("Music Genre: ")
sound = input("Sound: ")
body_part = input("Part of body: ")
print()

print("Your name is %s." % name)
print("You are a %s %s." % (adj_1, occupation))
print("Today you must %s the %s." % (verb_1, original_plural_noun))
print("The reason you are doing this is because the %s ate your %s." %(original_plural_noun, noun_1))
print("This is the last straw for you, they have went over the line, and for that they must be (VERB ENDING IN “ed”).")
print("You arm yourself with a (WEAPON) and put on your favorite (ARTICLE OF CLOTHING).")
print("After all of this, you do some extreme (TYPE OF WORKOUT).")
print("When you finally arrive at (ORIGINAL PLURAL NOUN)’s (PROPER NOUN [PLACE]) you start hyping yourself up by listening to (MUSIC GENRE).")
print("When you enter you have a glorious battle with (ORIGINAL PLURAL NOUN) that ends in your victory.")
print("As a sign of ultimate dominance you let out a fierce (SOUND).")
print("After the battle, you return home and take a long nap to rest your troubled (PART OF BODY).")
